version: 1
jobs:
  compile:
    image: node
    script:
      - npm install
      - npx oz compile
  test:
    image: node
    script:
      - npm install
      - npx oz compile && npm test
  deploy_to_rinkeby_manually:
    image: node
    type:
      name: ethereum/deploy
    script:
      - npm install
      - npx openzeppelin compile --no-interactive
      - npm run deploy:rinkeby_metamask
      - npx superblocks-cli collect-artifacts

stages:
  - build_and_test:
      jobs:
        - compile
        - test
  - deploy_to_testnets:
      jobs:
        - deploy_to_rinkeby_manually:
            when: manual
            filters:
              only:
                - master